# Generated by Django 6.0.5 on 2026-07-21 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='requested', max_length=15)),
                ('patient_notes', models.TextField(blank=True)),
                ('clinician_notes', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'db_table': 'consultations_consultation',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('quality_decline', 'Movement quality declining'), ('symmetry_concern', 'Persistent symmetry imbalance'), ('missed_sessions', 'Repeated missed sessions'), ('pain_increase', 'Pain level rising'), ('manual', 'Manually flagged by clinician')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open — awaiting review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action taken')], db_index=True, default='open', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'escalation',
                'verbose_name_plural': 'escalations',
                'db_table': 'consultations_escalation',
                'ordering': ['-created_at'],
            },
        ),
    ]
