# Generated by Django 6.0.5 on 2026-07-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('core', '0001_initial'),
        ('physio_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.patientprofile'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='clinician',
            field=models.ForeignKey(blank=True, help_text='Clinician who should review; null means unassigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_assigned', to='core.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.patientprofile'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_reviewed', to='core.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='physio_sessions.session'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'scheduled_at'], name='consultatio_patient_404e92_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['clinician', 'scheduled_at'], name='consultatio_clinici_18fad2_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='consultatio_status_787364_idx'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['patient', 'status'], name='consultatio_patient_110b25_idx'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['clinician', 'status'], name='consultatio_clinici_af126a_idx'),
        ),
    ]
