# Generated by Django 6.0.5 on 2026-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='initiated_by',
            field=models.CharField(choices=[('patient', 'Patient'), ('clinician', 'Clinician')], default='patient', max_length=10),
        ),
    ]
