# Generated by Django 6.0.5 on 2026-08-02 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_initiated_by'),
        ('core', '0012_slackplandraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('patient', 'Patient'), ('clinician', 'Clinician')], db_index=True, max_length=10)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_messages', to='core.clinicianprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_messages', to='core.patientprofile')),
            ],
            options={
                'verbose_name': 'care message',
                'verbose_name_plural': 'care messages',
                'db_table': 'consultations_caremessage',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='consultatio_patient_7222f1_idx'), models.Index(fields=['clinician', 'created_at'], name='consultatio_clinici_0ee369_idx')],
            },
        ),
    ]
