# Generated by Django 6.0.5 on 2026-07-21 15:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Derived from ended_at - started_at; stored for fast aggregation', null=True)),
                ('sets_completed', models.PositiveSmallIntegerField(default=0)),
                ('reps_completed', models.PositiveSmallIntegerField(default=0)),
                ('reps_target', models.PositiveSmallIntegerField()),
                ('sets_target', models.PositiveSmallIntegerField()),
                ('affected_side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('cues_triggered', models.JSONField(default=list, help_text='[{cue_text: str, trigger_count: int}]')),
                ('symmetry_warnings_count', models.PositiveSmallIntegerField(default=0)),
                ('low_confidence_frames_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Percentage of frames where required joints were low-confidence', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calibration', models.ForeignKey(blank=True, help_text='Which calibration was active during this session, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='catalogue.calibration')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalogue.exercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.patientprofile')),
                ('prescription', models.ForeignKey(blank=True, help_text='Snapshot FK; may be null if prescription was later deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='catalogue.prescription')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'sessions_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PainCheckin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pain_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('location_notes', models.CharField(blank=True, max_length=100)),
                ('checked_at', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_checkins', to='core.patientprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_checkins', to='physio_sessions.session')),
            ],
            options={
                'verbose_name': 'pain check-in',
                'verbose_name_plural': 'pain check-ins',
                'db_table': 'sessions_paincheckin',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['patient', '-started_at'], name='sessions_se_patient_2a5852_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['exercise'], name='sessions_se_exercis_fd7a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['prescription'], name='sessions_se_prescri_c66716_idx'),
        ),
        migrations.AddIndex(
            model_name='paincheckin',
            index=models.Index(fields=['patient', '-checked_at'], name='sessions_pa_patient_f2308b_idx'),
        ),
    ]
