from django.core.management.base import BaseCommand
from api.catalogue.models import Exercise

EXERCISES = [
    {
        "id": "heel-cord-stretch",
        "name": "Heel Cord Stretch",
        "category": "stretch",
        "camera_direction": "front",
        "rep_rule": "neutral → stretch → hold",
        "default_sets": 2,
        "default_reps": 4,
        "default_hold_seconds": 30,
        "default_days_per_week": "6–7",
        "tracking_notes": "Side camera; back leg ankle/footIndex landmarks must be visible.",
        "tracked_angles_config": {
            "ankle": {"points": ["knee", "ankle", "footIndex"], "side": "affected"},
        },
        "phases_config": [
            {"name": "neutral", "ankle": [88, 115]},
            {"name": "stretch",  "ankle": [50, 87]},
        ],
        "cues_config": {
            "ankle>92": "Lean forward more to feel the stretch in the calf",
        },
        "stage_images": ["standing", "calf-stretch"],
        "sort_order": 1,
    },
    {
        "id": "standing-quad-stretch",
        "name": "Standing Quadriceps Stretch",
        "category": "stretch",
        "camera_direction": "front",
        "rep_rule": "standing → stretch → hold",
        "default_sets": 1,
        "default_reps": 3,
        "default_hold_seconds": 45,
        "default_days_per_week": "4–5",
        "tracking_notes": "Side camera. Ankle landmark may be partially occluded when heel is raised; flag low-confidence.",
        "tracked_angles_config": {
            "knee": {"points": ["hip", "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "standing", "knee": [155, 180]},
            {"name": "stretch",  "knee": [30, 70]},
        ],
        "cues_config": {
            "knee>80": "Pull heel closer to your buttock for a deeper stretch",
        },
        "stage_images": ["standing", "quad-stretch"],
        "sort_order": 2,
    },
    {
        "id": "supine-hamstring-stretch",
        "name": "Supine Hamstring Stretch",
        "category": "stretch",
        "camera_direction": "front",
        "rep_rule": "flat → stretch → hold",
        "default_sets": 1,
        "default_reps": 3,
        "default_hold_seconds": 45,
        "default_days_per_week": "4–5",
        "tracking_notes": "Supine (lying) — side camera. Keep leg in sagittal plane for clean angle reads.",
        "tracked_angles_config": {
            "hip":  {"points": ["shoulder", "hip",  "knee"],  "side": "affected"},
            "knee": {"points": ["hip",      "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "flat",    "hip": [155, 180], "knee": [155, 180]},
            {"name": "stretch", "hip": [60, 110],  "knee": [130, 180]},
        ],
        "cues_config": {
            "knee<120": "Try to straighten your knee more while holding the stretch",
        },
        "stage_images": ["lying-flat", "lying-leg-raised"],
        "sort_order": 3,
    },
    {
        "id": "half-squats",
        "name": "Half Squats",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "standing → squat → standing",
        "default_sets": 3,
        "default_reps": 10,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "phase_confirmation_ms": 300,
        "max_cues": 1,
        "tracking_warning": "Face the camera and keep both feet, knees, hips, and shoulders fully visible.",
        "tracked_angles_config": {
            "leftKnee":  {"points": ["leftHip",  "leftKnee",  "leftAnkle"]},
            "rightKnee": {"points": ["rightHip", "rightKnee", "rightAnkle"]},
            "leftHip":   {"points": ["leftShoulder",  "leftHip",  "leftKnee"]},
            "rightHip":  {"points": ["rightShoulder", "rightHip", "rightKnee"]},
            "torsoLean": {"points": ["leftShoulder", "rightShoulder", "leftHip", "rightHip"]},
            "leftKneeForwardRatio":  {"points": ["nose", "leftKnee",  "leftAnkle",  "leftFootIndex"]},
            "rightKneeForwardRatio": {"points": ["nose", "rightKnee", "rightAnkle", "rightFootIndex"]},
        },
        "phases_config": [
            {
                "name": "standing",
                "leftKnee": [160, 180], "rightKnee": [160, 180],
                "leftHip": [155, 180],  "rightHip": [155, 180],
                "torsoLean": [0, 25],
                "leftKneeForwardRatio": [-1, 0.15], "rightKneeForwardRatio": [-1, 0.15],
            },
            {
                "name": "squat",
                "leftKnee": [90, 130], "rightKnee": [90, 130],
                "leftHip": [90, 135],  "rightHip": [90, 135],
                "torsoLean": [0, 40],
                "leftKneeForwardRatio": [-1, 0.15], "rightKneeForwardRatio": [-1, 0.15],
            },
        ],
        "cues_config": {
            "leftKnee<90":  "Don't go too deep — this is a half squat only",
            "rightKnee<90": "Don't go too deep — this is a half squat only",
            "torsoLean>40": "Lift your chest slightly — avoid leaning too far forward",
            "leftKneeForwardRatio>0.15":  "Move your left knee back so it stays over your foot",
            "rightKneeForwardRatio>0.15": "Move your right knee back so it stays over your foot",
            "kneeDiff>15": "Keep both knees bending equally",
        },
        "calibration_config": {
            "startPhase": "standing",
            "targetPhase": "squat",
            "captureKeys": ["leftKnee", "rightKnee", "leftHip", "rightHip", "torsoLean", "leftKneeForwardRatio", "rightKneeForwardRatio"],
            "personalizedKeys": ["leftKnee", "rightKnee", "leftHip", "rightHip"],
            "toleranceDegrees": 8,
            "safeRanges": {
                "start": {
                    "leftKnee": [145, 180], "rightKnee": [145, 180],
                    "leftHip": [145, 180],  "rightHip": [145, 180],
                    "torsoLean": [0, 25],
                    "leftKneeForwardRatio": [-1, 0.15], "rightKneeForwardRatio": [-1, 0.15],
                },
                "target": {
                    "leftKnee": [90, 145], "rightKnee": [90, 145],
                    "leftHip": [90, 150],  "rightHip": [90, 150],
                    "torsoLean": [0, 40],
                    "leftKneeForwardRatio": [-1, 0.15], "rightKneeForwardRatio": [-1, 0.15],
                },
            },
            "captureErrors": {
                "leftKnee":  "Use a comfortable half-squat depth and do not bend past 90°.",
                "rightKnee": "Use a comfortable half-squat depth and do not bend past 90°.",
                "leftHip":   "Use a smaller, comfortable movement for this calibration.",
                "rightHip":  "Use a smaller, comfortable movement for this calibration.",
                "torsoLean": "Lift your chest and try the measurement again.",
                "leftKneeForwardRatio":  "Move your knees back over your feet, then try again.",
                "rightKneeForwardRatio": "Move your knees back over your feet, then try again.",
            },
        },
        "symmetry_config": {"joint": "knee", "maxDiffDeg": 15},
        "stage_images": ["standing", "squat", "standing"],
        "sort_order": 4,
    },
    {
        "id": "hamstring-curls",
        "name": "Hamstring Curls",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "standing → curled → standing",
        "default_sets": 3,
        "default_reps": 10,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "tracking_warning": "Ankle moves behind the body — depth inference is less accurate at peak curl. Angle readings are approximate.",
        "tracked_angles_config": {
            "knee": {"points": ["hip", "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "standing", "knee": [160, 180]},
            {"name": "curled",   "knee": [30, 70]},
        ],
        "cues_config": {
            "knee>90": "Curl higher — bring your heel up toward the ceiling",
        },
        "stage_images": ["standing", "knee-curled", "standing"],
        "sort_order": 5,
    },
    {
        "id": "calf-raises",
        "name": "Calf Raises",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "flat → raised → flat",
        "default_sets": 2,
        "default_reps": 10,
        "default_hold_seconds": 0,
        "default_days_per_week": "6–7",
        "tracked_angles_config": {
            "footInclination": {"points": ["heel", "footIndex"], "side": "affected"},
        },
        "phases_config": [
            {"name": "flat",   "footInclination": [0, 12]},
            {"name": "raised", "footInclination": [18, 50]},
        ],
        "cues_config": {
            "footInclination<18": "Rise higher onto your toes",
        },
        "stage_images": ["standing", "calf-raised", "standing"],
        "sort_order": 6,
    },
    {
        "id": "leg-extensions",
        "name": "Leg Extensions (Seated)",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "seated → extended → seated",
        "default_sets": 3,
        "default_reps": 10,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "tracked_angles_config": {
            "knee": {"points": ["hip", "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "seated",   "knee": [80, 105]},
            {"name": "extended", "knee": [155, 180]},
        ],
        "cues_config": {
            "knee<150": "Try to straighten your leg fully at the top",
        },
        "stage_images": ["seated", "seated-leg-extended", "seated"],
        "sort_order": 7,
    },
    {
        "id": "straight-leg-raises-supine",
        "name": "Straight-Leg Raises (Supine)",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "flat → raised → flat",
        "default_sets": 3,
        "default_reps": 10,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "tracked_angles_config": {
            "hip":  {"points": ["shoulder", "hip",  "knee"],  "side": "affected"},
            "knee": {"points": ["hip",      "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "flat",   "hip": [155, 180], "knee": [155, 180]},
            {"name": "raised", "hip": [125, 155], "knee": [155, 180]},
        ],
        "cues_config": {
            "knee<150": "Keep your leg straight — don't bend the knee",
            "hip<120":  "Lower leg slightly — 6 to 10 inches off the floor is enough",
        },
        "stage_images": ["lying-flat", "lying-leg-raised", "lying-flat"],
        "sort_order": 8,
    },
    {
        "id": "straight-leg-raises-prone",
        "name": "Straight-Leg Raises (Prone)",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "flat → raised → flat",
        "default_sets": 3,
        "default_reps": 10,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "tracking_notes": "Prone position — face down. Landmark visibility will be low on many joints. Flag liberally.",
        "tracking_warning": "High occlusion risk in prone position; side camera essential.",
        "tracked_angles_config": {
            "hip":  {"points": ["shoulder", "hip",  "knee"],  "side": "affected"},
            "knee": {"points": ["hip",      "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "flat",   "hip": [165, 185], "knee": [155, 180]},
            {"name": "raised", "hip": [185, 210], "knee": [155, 180]},
        ],
        "cues_config": {
            "knee<150": "Keep your knee straight while lifting",
        },
        "stage_images": ["prone-flat", "prone-leg-raised", "prone-flat"],
        "sort_order": 9,
    },
    {
        "id": "hip-abduction",
        "name": "Hip Abduction",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "rest → abducted → rest",
        "default_sets": 3,
        "default_reps": 20,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "tracking_notes": "Side-lying; front camera shows frontal-plane motion. Top-side hip/knee landmarks may partially occlude. Flag aggressively.",
        "tracking_warning": "Side-lying position: expect frequent low-confidence flags on affected-side landmarks.",
        "tracked_angles_config": {
            "hip": {"points": ["shoulder", "hip", "knee"], "side": "affected"},
        },
        "phases_config": [
            {"name": "rest",     "hip": [160, 180]},
            {"name": "abducted", "hip": [125, 145]},
        ],
        "cues_config": {
            "hip>150": "Lift the leg higher — aim for a 45° angle from your body",
        },
        "stage_images": ["side-lying", "side-lying-abducted", "side-lying"],
        "sort_order": 10,
    },
    {
        "id": "hip-adduction",
        "name": "Hip Adduction",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "rest → adducted → rest",
        "default_sets": 3,
        "default_reps": 20,
        "default_hold_seconds": 5,
        "default_days_per_week": "4–5",
        "tracking_notes": "Side-lying on injured side. Bottom leg likely partially occluded by upper body. Expect very high low-confidence rate.",
        "tracking_warning": "Most reliable when patient is visible from a 45° elevated front angle.",
        "tracked_angles_config": {
            "hip": {"points": ["shoulder", "hip", "knee"], "side": "affected"},
        },
        "phases_config": [
            {"name": "rest",     "hip": [160, 180]},
            {"name": "adducted", "hip": [145, 159]},
        ],
        "cues_config": {
            "hip>163": "Lift the bottom leg off the floor — 6 to 8 inches is the target",
        },
        "stage_images": ["side-lying", "side-lying-abducted", "side-lying"],
        "sort_order": 11,
    },
    {
        "id": "leg-presses",
        "name": "Leg Presses (Elastic Band)",
        "category": "strengthening",
        "camera_direction": "front",
        "rep_rule": "bent → extended → bent",
        "default_sets": 3,
        "default_reps": 10,
        "default_hold_seconds": 2,
        "default_days_per_week": "4–5",
        "tracking_notes": "Supine. Side camera gives cleanest sagittal-plane read.",
        "tracked_angles_config": {
            "hip":  {"points": ["shoulder", "hip",  "knee"],  "side": "affected"},
            "knee": {"points": ["hip",      "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "bent",     "hip": [70, 110],  "knee": [70, 105]},
            {"name": "extended", "hip": [140, 180], "knee": [150, 180]},
        ],
        "cues_config": {
            "knee<150": "Press fully against the band — straighten your leg completely",
        },
        "stage_images": ["lying-knees-bent", "lying-legs-extended", "lying-knees-bent"],
        "sort_order": 12,
    },
    {
        "id": "ankle_pumps",
        "name": "Ankle Pumps",
        "category": "mobility",
        "camera_direction": "side",
        "rep_rule": "toes_up → toes_down → toes_up",
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": 0,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 300,
        "max_cues": 1,
        "tracking_warning": "Prototype primary-motion tracking. Use only with a clinician-approved dose and restrictions.",
        "tracking_notes": "Supported straight-leg variant only; checks ankle direction and knee angle.",
        "tracked_angles_config": {
            "ankle": {"points": ["knee", "ankle", "footIndex"], "side": "affected"},
            "knee": {"points": ["hip", "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "toes_up", "ankle": [45, 88], "knee": [145, 180]},
            {"name": "toes_down", "ankle": [98, 150], "knee": [145, 180]},
        ],
        "cues_config": {
            "knee<145": "Keep your knee and upper leg still while moving your ankle",
            "ankle>150": "Use a smaller, comfortable ankle movement",
        },
        "stage_images": ["ankle-toes-up", "ankle-toes-down", "ankle-toes-up"],
        "sort_order": 13,
    },
    {
        "id": "heel_slides",
        "name": "Heel Slides",
        "category": "mobility",
        "camera_direction": "side",
        "rep_rule": "knee_bent → leg_extended → knee_bent",
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": 0,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 300,
        "tracking_warning": "Prototype primary-motion tracking. Use only with a clinician-approved dose and restrictions.",
        "tracking_notes": "Counts knee bending and straightening only; does not verify heel contact or pelvic stability.",
        "tracked_angles_config": {
            "knee": {"points": ["hip", "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "knee_bent", "knee": [60, 120]},
            {"name": "leg_extended", "knee": [150, 180]},
        ],
        "cues_config": {},
        "stage_images": ["heel-slide-bent", "heel-slide-extended", "heel-slide-bent"],
        "sort_order": 14,
    },
    {
        "id": "hip_bridge",
        "name": "Hip Bridge",
        "category": "strengthening",
        "camera_direction": "side",
        "rep_rule": "pelvis_down → bridge → pelvis_down",
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": 0,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 300,
        "max_cues": 1,
        "tracking_warning": "Prototype primary-motion tracking. Use only with a clinician-approved dose and restrictions.",
        "tracking_notes": "Checks hip alignment and knee angle; does not assess muscle activation or lumbar curvature.",
        "tracked_angles_config": {
            "hip": {"points": ["shoulder", "hip", "knee"], "side": "affected"},
            "knee": {"points": ["hip", "knee", "ankle"], "side": "affected"},
        },
        "phases_config": [
            {"name": "pelvis_down", "hip": [105, 148], "knee": [55, 125]},
            {"name": "bridge", "hip": [155, 180], "knee": [55, 125]},
        ],
        "cues_config": {
            "knee<55": "Move your foot slightly farther away to keep the knee comfortable",
            "knee>125": "Move your foot slightly closer before lifting again",
        },
        "stage_images": ["bridge-down", "bridge-up", "bridge-down"],
        "sort_order": 15,
    },
    {
        "id": "wrist_extension_stretch",
        "name": "Wrist Extension Stretch",
        "category": "stretch",
        "camera_direction": "side",
        "rep_rule": "neutral → wrist_extended → hold",
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": None,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 350,
        "max_cues": 1,
        "tracking_warning": "Engineering Pose + Hand sequence prototype. The tracking timer is not the prescribed stretch duration.",
        "tracking_notes": "Runs Pose and Hand Landmarker on the same frame; normalized image coordinates are used for cross-model wrist geometry.",
        "tracked_angles_config": {
            "elbow": {"source": "pose"},
            "wristBend": {"source": "pose_and_hand"},
            "palmDown": {"source": "hand"},
            "forearmHorizontal": {"source": "pose"},
            "forearmVelocity": {"source": "pose_time_window"},
            "wristMatch": {"source": "pose_and_hand"},
        },
        "phases_config": [
            {"name": "neutral", "elbow": [150, 180], "wristBend": [-12, 12], "palmDown": [0.35, 1], "forearmHorizontal": [0.45, 1], "forearmVelocity": [0, 0.3], "wristMatch": [0, 0.14]},
            {"name": "wrist_extended", "elbow": [150, 180], "wristBend": [-70, -15], "palmDown": [0.35, 1], "forearmHorizontal": [0.45, 1], "forearmVelocity": [0, 0.3], "wristMatch": [0, 0.14]},
        ],
        "cues_config": {
            "elbow<150": "Straighten your working elbow gently",
            "palmDown<0.35": "Turn the working palm downward",
            "forearmVelocity>0.3": "Keep your forearm still and move only at the wrist",
        },
        "stage_images": [],
        "sort_order": 16,
    },
    {
        "id": "wrist_flexion_stretch",
        "name": "Wrist Flexion Stretch",
        "category": "stretch",
        "camera_direction": "side",
        "rep_rule": "neutral → wrist_flexed → hold",
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": None,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 350,
        "max_cues": 1,
        "tracking_warning": "Engineering Pose + Hand sequence prototype. The tracking timer is not the prescribed stretch duration.",
        "tracking_notes": "Runs Pose and Hand Landmarker on the same frame; normalized image coordinates are used for cross-model wrist geometry.",
        "tracked_angles_config": {
            "elbow": {"source": "pose"},
            "wristBend": {"source": "pose_and_hand"},
            "palmDown": {"source": "hand"},
            "forearmHorizontal": {"source": "pose"},
            "forearmVelocity": {"source": "pose_time_window"},
            "wristMatch": {"source": "pose_and_hand"},
        },
        "phases_config": [
            {"name": "neutral", "elbow": [150, 180], "wristBend": [-12, 12], "palmDown": [0.35, 1], "forearmHorizontal": [0.45, 1], "forearmVelocity": [0, 0.3], "wristMatch": [0, 0.14]},
            {"name": "wrist_flexed", "elbow": [150, 180], "wristBend": [15, 70], "palmDown": [0.35, 1], "forearmHorizontal": [0.45, 1], "forearmVelocity": [0, 0.3], "wristMatch": [0, 0.14]},
        ],
        "cues_config": {
            "elbow<150": "Straighten your working elbow gently",
            "palmDown<0.35": "Turn the working palm downward",
            "forearmVelocity>0.3": "Keep your forearm still and move only at the wrist",
        },
        "stage_images": [],
        "sort_order": 17,
    },
    {
        "id": "tendon_glides",
        "name": "Tendon Glides",
        "category": "mobility",
        "camera_direction": "front",
        "rep_rule": "open_hand → hook_fist → open_hand → full_fist → open_hand → tabletop → open_hand → straight_fist → open_hand",
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": 0,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 350,
        "tracking_warning": "Engineering hand-shape sequence prototype; requires clinician-labelled real-video validation.",
        "tracking_notes": "Counts only the complete ordered sequence with a stable open-hand return between shapes.",
        "tracked_angles_config": {
            "handShape": {"source": "hand_shape_rules"},
            "handShapeScore": {"source": "hand_shape_rules"},
            "handFrameReady": {"source": "hand_framing_gate"},
        },
        "phases_config": [
            {"name": "open_hand", "handShape": {"equals": "open_hand"}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
            {"name": "hook_fist", "handShape": {"equals": "hook_fist"}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
            {"name": "full_fist", "handShape": {"equals": "full_fist"}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
            {"name": "tabletop", "handShape": {"equals": "tabletop"}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
            {"name": "straight_fist", "handShape": {"equals": "straight_fist"}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
        ],
        "cues_config": {},
        "stage_images": [],
        "sort_order": 18,
    },
]


def prototype_record(
    exercise_id,
    name,
    category,
    camera_direction,
    rep_rule,
    phases,
    measurements,
    warning,
    sort_order,
    cues=None,
):
    """Create a conservative API record for an unvalidated live prototype."""
    return {
        "id": exercise_id,
        "name": name,
        "category": category,
        "camera_direction": camera_direction,
        "rep_rule": rep_rule,
        "default_sets": 1,
        "default_reps": 1,
        "default_hold_seconds": None if category == "stretch" else 0,
        "default_days_per_week": "prescribed",
        "phase_confirmation_ms": 350,
        "max_cues": 1,
        "tracking_warning": warning,
        "tracking_notes": (
            "Engineering recognition prototype. Camera observations do not "
            "establish clinical safety and require real-video validation."
        ),
        "tracked_angles_config": {
            measurement: {"source": "exercise_tracking_adapter"}
            for measurement in measurements
        },
        "phases_config": phases,
        "cues_config": cues or {},
        "stage_images": [],
        "sort_order": sort_order,
    }


EXERCISES.extend([
    prototype_record(
        "forearm_supination_pronation_strengthening",
        "Forearm Supination and Pronation",
        "strengthening",
        "front",
        "neutral → palm_up → neutral → palm_down → neutral",
        [
            {"name": "neutral", "elbow": [70, 110], "palmDirection": {"oneOf": ["left", "right", "toward_camera", "away_from_camera"]}, "handFrameReady": [1, 1], "wristMatch": [0, 0.14], "upperArmMotion": [0, 0.25]},
            {"name": "palm_up", "elbow": [70, 110], "palmDirection": {"equals": "upward"}, "handFrameReady": [1, 1], "wristMatch": [0, 0.14], "upperArmMotion": [0, 0.25]},
            {"name": "palm_down", "elbow": [70, 110], "palmDirection": {"equals": "downward"}, "handFrameReady": [1, 1], "wristMatch": [0, 0.14], "upperArmMotion": [0, 0.25]},
        ],
        ["elbow", "palmDirection", "handFrameReady", "wristMatch", "upperArmMotion"],
        "Pose + Hand palm-rotation prototype; object weight, grip and resistance are not observable.",
        19,
    ),
    prototype_record(
        "stress_ball_squeeze",
        "Stress Ball Squeeze",
        "strengthening",
        "front",
        "open_hand → closed_hand → open_hand",
        [
            {"name": "open_hand", "handShape": {"equals": "open_hand"}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
            {"name": "closed_hand", "handShape": {"oneOf": ["full_fist", "straight_fist"]}, "handShapeScore": [0.7, 1], "handFrameReady": [1, 1]},
        ],
        ["handShape", "handShapeScore", "handFrameReady"],
        "Partial hand-shape tracker; the ball may occlude fingers and grip force is not observable.",
        20,
    ),
    prototype_record(
        "ankle_rotations",
        "Ankle Rotations",
        "mobility",
        "front",
        "neutral → clockwise_circle → neutral → counterclockwise_circle → neutral",
        [
            {"name": "neutral", "toeMotion": [0, 0.06], "legMotion": [0, 0.12], "circleDirection": {"equals": "none"}, "circleScore": [0, 0.45]},
            {"name": "clockwise_circle", "toeMotion": [0.08, 1.5], "legMotion": [0, 0.12], "circleDirection": {"equals": "clockwise"}, "circleScore": [0.35, 1]},
            {"name": "counterclockwise_circle", "toeMotion": [0.08, 1.5], "legMotion": [0, 0.12], "circleDirection": {"equals": "counterclockwise"}, "circleScore": [0.35, 1]},
        ],
        ["toeMotion", "legMotion", "circleDirection", "circleScore"],
        "Toe-trajectory proxy; inversion and eversion cannot be fully measured from one foot-tip landmark.",
        21,
    ),
    prototype_record(
        "ankle_range_of_motion",
        "Ankle Range of Motion",
        "mobility",
        "front",
        "foot_ready → letter_motion → foot_ready",
        [
            {"name": "foot_ready", "toeMotion": [0, 0.06], "legMotion": [0, 0.12]},
            {"name": "letter_motion", "toeMotion": [0.12, 1.8], "legMotion": [0, 0.12]},
        ],
        ["toeMotion", "legMotion"],
        "Recognises deliberate ankle-relative motion but does not classify individual alphabet letters.",
        22,
    ),
    prototype_record(
        "ankle_dorsiflexion_plantar_flexion",
        "Ankle Dorsiflexion and Plantar Flexion",
        "strengthening",
        "side",
        "toes_up → toes_down → toes_up",
        [
            {"name": "toes_up", "ankle": [45, 88], "knee": [60, 130]},
            {"name": "toes_down", "ankle": [98, 150], "knee": [60, 130]},
        ],
        ["ankle", "knee"],
        "Primary ankle-direction tracker; resistance-band tension and anchor safety are not observable.",
        23,
    ),
    prototype_record(
        "supported_single_leg_balance",
        "Supported Single-Leg Balance",
        "mobility",
        "front",
        "both_feet_down → supported_single_leg → both_feet_down",
        [
            {"name": "both_feet_down", "workingFootClearance": [0, 0.05], "standingKnee": [140, 180], "torsoLean": [0, 20]},
            {"name": "supported_single_leg", "workingFootClearance": [0.08, 0.5], "standingKnee": [140, 180], "torsoLean": [0, 20]},
        ],
        ["workingFootClearance", "standingKnee", "torsoLean"],
        "Safety-limited foot-lift proxy; support grip, stability and fall risk are not observable.",
        24,
    ),
    prototype_record(
        "clamshell",
        "Clamshell",
        "strengthening",
        "front",
        "knees_together → upper_knee_raised → knees_together",
        [
            {"name": "knees_together", "kneeSeparation": [0, 0.18], "ankleSeparation": [0, 0.3]},
            {"name": "upper_knee_raised", "kneeSeparation": [0.25, 1.2], "ankleSeparation": [0, 0.3]},
        ],
        ["kneeSeparation", "ankleSeparation"],
        "Knee-separation prototype limited by side-lying landmark overlap and occlusion.",
        25,
    ),
    prototype_record(
        "supported_forward_step_up",
        "Supported Forward Step-Up",
        "strengthening",
        "side",
        "floor → foot_on_step → body_raised → foot_on_step → floor",
        [
            {"name": "floor", "workingFootClearance": [0, 0.1], "knee": [145, 180], "torsoLean": [0, 25]},
            {"name": "foot_on_step", "workingFootClearance": [0.12, 0.65], "knee": [60, 144], "torsoLean": [0, 25]},
            {"name": "body_raised", "workingFootClearance": [0.12, 0.65], "knee": [145, 178], "torsoLean": [0, 25]},
        ],
        ["workingFootClearance", "knee", "torsoLean"],
        "Step-motion proxy; step stability, full-foot contact and rail grip are not observable.",
        26,
    ),
    prototype_record(
        "walking_progression",
        "Walking Progression",
        "mobility",
        "side",
        "feet_aligned → working_foot_forward → other_foot_forward → feet_aligned",
        [
            {"name": "feet_aligned", "footLead": [-0.15, 0.15], "torsoLean": [0, 25]},
            {"name": "working_foot_forward", "footLead": [0.2, 1.5], "torsoLean": [0, 25]},
            {"name": "other_foot_forward", "footLead": [-1.5, -0.2], "torsoLean": [0, 25]},
        ],
        ["footLead", "torsoLean"],
        "Alternating-step proxy; endurance, hazards and clinically accurate gait events are not verified.",
        27,
    ),
    prototype_record(
        "walking_with_mobility_aid",
        "Walking with a Mobility Aid",
        "mobility",
        "side",
        "ready → aid_forward_proxy → recovering_leg_forward → other_leg_through → ready",
        [
            {"name": "ready", "footLead": [-0.15, 0.15], "handMotion": [0, 0.08], "torsoLean": [0, 30]},
            {"name": "aid_forward_proxy", "footLead": [-0.15, 0.15], "handMotion": [0.12, 1.5], "torsoLean": [0, 30]},
            {"name": "recovering_leg_forward", "footLead": [0.2, 1.5], "torsoLean": [0, 30]},
            {"name": "other_leg_through", "footLead": [-1.5, -0.2], "torsoLean": [0, 30]},
        ],
        ["footLead", "handMotion", "torsoLean"],
        "Hand-motion proxy only; the aid itself and weight-bearing restrictions are not verified.",
        28,
    ),
    prototype_record(
        "single_knee_to_chest_stretch",
        "Single Knee-to-Chest Stretch",
        "stretch",
        "side",
        "both_knees_bent → knee_to_chest → hold",
        [
            {"name": "both_knees_bent", "hip": [70, 135], "knee": [55, 125]},
            {"name": "knee_to_chest", "hip": [10, 65], "knee": [30, 125]},
        ],
        ["hip", "knee"],
        "Primary-position tracker; pain, numbness, tingling and applied pressure are not observable.",
        29,
    ),
    prototype_record(
        "hip_flexor_stretch",
        "Hip Flexor Stretch",
        "stretch",
        "side",
        "setup → stretch → hold",
        [
            {"name": "setup", "hip": [70, 135], "oppositeHip": [100, 180]},
            {"name": "stretch", "hip": [10, 65], "oppositeHip": [145, 180]},
        ],
        ["hip", "oppositeHip"],
        "Bed-edge position proxy; surface safety, lumbar comfort, force and pain are not observable.",
        30,
    ),
    prototype_record(
        "pendulum",
        "Shoulder Pendulum",
        "mobility",
        "side",
        "supported_lean → gentle_swing → supported_lean",
        [
            {"name": "supported_lean", "torsoLean": [20, 70], "elbow": [145, 180], "wristMotion": [0, 0.06]},
            {"name": "gentle_swing", "torsoLean": [20, 70], "elbow": [145, 180], "wristMotion": [0.08, 0.9]},
        ],
        ["torsoLean", "elbow", "wristMotion"],
        "Wrist-trajectory proxy; passive shoulder motion and support stability are not observable.",
        31,
    ),
    prototype_record(
        "crossover_arm_stretch",
        "Crossover Arm Stretch",
        "stretch",
        "front",
        "arms_relaxed → arm_across_chest → hold",
        [
            {"name": "arms_relaxed", "shoulder": [0, 45], "wristAcrossMidline": [-2, 0.05], "torsoLean": [0, 20]},
            {"name": "arm_across_chest", "shoulder": [55, 125], "wristAcrossMidline": [0.1, 2], "torsoLean": [0, 20]},
        ],
        ["shoulder", "wristAcrossMidline", "torsoLean"],
        "Arm-position tracker; elbow pressure, stretch force and pain are not observable.",
        32,
    ),
    prototype_record(
        "standing_row",
        "Standing Row",
        "strengthening",
        "front",
        "arm_forward → elbow_pulled_back → arm_forward",
        [
            {"name": "arm_forward", "elbow": [145, 180], "torsoLean": [0, 25]},
            {"name": "elbow_pulled_back", "elbow": [60, 120], "torsoLean": [0, 25]},
        ],
        ["elbow", "torsoLean"],
        "Primary elbow-motion tracker; band resistance, anchor security and scapular activation are not observable.",
        33,
    ),
    prototype_record(
        "external_rotation_with_resistance_band",
        "External Rotation with Resistance Band",
        "strengthening",
        "front",
        "forearm_forward → forearm_rotated_out → forearm_forward",
        [
            {"name": "forearm_forward", "elbow": [70, 110], "wristOutwardRatio": [0, 0.35], "torsoLean": [0, 20]},
            {"name": "forearm_rotated_out", "elbow": [70, 110], "wristOutwardRatio": [0.55, 1], "torsoLean": [0, 20]},
        ],
        ["elbow", "wristOutwardRatio", "torsoLean"],
        "Primary forearm-motion tracker; band resistance, anchor safety and elbow contact are not observable.",
        34,
    ),
    prototype_record(
        "shoulder_forward_elevation_assisted",
        "Assisted Shoulder Forward Elevation",
        "mobility",
        "front",
        "arms_down → assisted_elevation → arms_down",
        [
            {"name": "arms_down", "shoulder": [0, 40], "handProximity": [0, 0.65], "torsoLean": [0, 20]},
            {"name": "assisted_elevation", "shoulder": [70, 155], "handProximity": [0, 0.65], "torsoLean": [0, 20]},
        ],
        ["shoulder", "handProximity", "torsoLean"],
        "Clinician-target prototype; assisting arm and post-operative height restrictions are not inferred.",
        35,
    ),
])


class Command(BaseCommand):
    help = "Seed exercise catalogue from registry.js data"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete all existing exercises before seeding",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            Exercise.objects.all().delete()
            self.stdout.write(self.style.WARNING("Cleared all existing exercises."))

        created = updated = 0
        for data in EXERCISES:
            _, is_new = Exercise.objects.update_or_create(
                id=data["id"],
                defaults={k: v for k, v in data.items() if k != "id"},
            )
            if is_new:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done — {created} created, {updated} updated. "
                f"{Exercise.objects.filter(is_active=True).count()} exercises active."
            )
        )
