# Generated by Django 6.0.5 on 2026-07-21 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('affected_side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('captured_at', models.DateTimeField()),
                ('start_measurements', models.JSONField(help_text='{key: {median: float, variability: float, sampleCount: int}}')),
                ('target_measurements', models.JSONField(help_text='{key: {median: float, variability: float, repetitions: int}}')),
                ('phase_ranges', models.JSONField(help_text='{phaseName: {key: [min_angle, max_angle]}}')),
                ('natural_knee_difference', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'calibration',
                'verbose_name_plural': 'calibrations',
                'db_table': 'catalogue_calibration',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('strengthening', 'Strengthening'), ('stretch', 'Stretch')], db_index=True, max_length=15)),
                ('camera_direction', models.CharField(choices=[('front', 'Front'), ('side', 'Side')], default='front', max_length=10)),
                ('rep_rule', models.CharField(help_text="e.g. 'standing → squat → standing'", max_length=120)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps', models.PositiveSmallIntegerField(default=10)),
                ('default_hold_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_days_per_week', models.CharField(default='4–5', max_length=10)),
                ('phase_confirmation_ms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_cues', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tracking_notes', models.TextField(blank=True)),
                ('tracking_warning', models.TextField(blank=True)),
                ('tracked_angles_config', models.JSONField(help_text='Map of angle names to {points, side?}')),
                ('phases_config', models.JSONField(help_text='List of phase objects {name, angleKey: [min, max], ...}')),
                ('cues_config', models.JSONField(help_text='Map of condition strings to cue text')),
                ('calibration_config', models.JSONField(blank=True, help_text='Calibration block: {startPhase, targetPhase, captureKeys, personalizedKeys, toleranceDegrees, safeRanges, captureErrors}', null=True)),
                ('symmetry_config', models.JSONField(blank=True, help_text='{joint: str, maxDiffDeg: int}', null=True)),
                ('stage_images', models.JSONField(blank=True, help_text='Ordered list of pose image keys for the pose strip', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'db_table': 'catalogue_exercise',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('hold_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days_per_week', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'db_table': 'catalogue_prescription',
                'ordering': ['-valid_from'],
            },
        ),
    ]
