# Generated by Django 6.0.5 on 2026-07-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='core.patientprofile'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category', 'is_active'], name='catalogue_e_categor_469142_idx'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='catalogue.exercise'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='clinician',
            field=models.ForeignKey(blank=True, help_text='Null for self-assigned wellness-path prescriptions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='catalogue.exercise'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patientprofile'),
        ),
        migrations.AddIndex(
            model_name='calibration',
            index=models.Index(fields=['patient', 'exercise', 'is_active'], name='catalogue_c_patient_23cc7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='calibration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'exercise'), name='unique_active_calibration_per_patient_exercise'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'exercise', 'is_active'], name='catalogue_p_patient_a5a19e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinician'], name='catalogue_p_clinici_9a11c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'exercise'), name='unique_active_prescription_per_patient_exercise'),
        ),
    ]
