# Generated by Django 6.0.5 on 2026-07-21 15:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('clinician', 'Clinician'), ('admin', 'Admin')], db_index=True, default='patient', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'core_user',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'clinician'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clinician profile',
                'verbose_name_plural': 'clinician profiles',
                'db_table': 'core_clinicianprofile',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(choices=[('stronger_knees', 'Stronger knees'), ('better_balance', 'Better balance'), ('less_stiffness', 'Move with less stiffness'), ('stay_active', 'Stay active')], default='stronger_knees', max_length=30)),
                ('activity_level', models.CharField(choices=[('lightly_active', 'Lightly active'), ('mostly_seated', 'Mostly seated'), ('active_most_days', 'Active most days')], default='lightly_active', max_length=20)),
                ('mobility_status', models.CharField(choices=[('independent', 'Independent'), ('walking_aid', 'Use a walking aid'), ('needs_person', 'Need another person nearby')], default='independent', max_length=25)),
                ('focus_side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], default='right', max_length=5)),
                ('cue_style', models.CharField(choices=[('gentle', 'Gentle and encouraging'), ('direct', 'Short and direct'), ('detailed', 'Explain each correction')], default='gentle', max_length=10)),
                ('care_path', models.CharField(choices=[('wellness', 'General wellness'), ('clinician', 'Physiotherapist-prescribed rehabilitation')], default='wellness', max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('medical_history', models.TextField(blank=True)),
                ('low_risk_acknowledged', models.BooleanField(default=False)),
                ('primary_clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.clinicianprofile')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient profile',
                'verbose_name_plural': 'patient profiles',
                'db_table': 'core_patientprofile',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['care_path'], name='core_patien_care_pa_359bef_idx'), models.Index(fields=['primary_clinician'], name='core_patien_primary_0165c1_idx')],
            },
        ),
    ]
