# Generated by Django 6.0.5 on 2026-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patientprofile_goal_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='slack_thread_ts',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
