# Generated by Django 6.0.5 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_patientprofile_slack_thread_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="wellness_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="wellness_plan_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
