# Generated by Django 6.0.5 on 2026-07-29 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patientprofile_wellness_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianprofile',
            name='slack_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='SlackLinkCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_link_codes', to='core.clinicianprofile')),
            ],
            options={
                'db_table': 'core_slacklinkcode',
                'ordering': ['-created_at'],
            },
        ),
    ]
