# Generated by Django 6.0.5 on 2026-07-29 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clinicianprofile_slack_user_id_slacklinkcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackPlanDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.JSONField()),
                ('preferences', models.JSONField()),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_plan_drafts', to='core.clinicianprofile')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_plan_draft', to='core.patientprofile')),
            ],
            options={
                'db_table': 'core_slackplandraft',
                'ordering': ['-updated_at'],
            },
        ),
    ]
